modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\User;
use app\models\Account;
use app\models\Profile;
use app\modules\admin\models\Language;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
	public function init() {

	    parent::init();
	    // $this->layout = '@app/modules/admin/views/layouts/main';
	    // custom initialization code goes here
	}

    public function actionError()
    {
        return $this->render('error');
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        if (!$session->has('language')) {
            $session->set('language', 'fr');
        }
        
        $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
        if (!empty($profile)) {
            $session->set('username',$profile->name);
            $name = $profile->name;
        }else{
            $name = '';
        }
        
        return $this->render('index',[
            'lang'=>$session->get('language'),
            'name'=>$name,
        ]);
    }

    public function actionLanguage()
    {
        $language = new Language();
        $session = Yii::$app->session;
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $alert='';
        if ($language->load(Yii::$app->request->post())) {
            $session->set('language', $language->lang);
            $alert = '<div class="alert alert-success alert-dismissible fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><h4><i class="icon fa fa-check"></i> Success!</h4>Success to Change Language.</div>';
        }
        if ($language->lang) {
            $session->set('language', $language->lang);
        }
        return $this->render('language',[
            'alert'=>$alert,
            'language'=>$language,]);
    }

    public function actionRegister()
    {
        $this->layout = "@app/modules/admin/views/layouts/main-login";

        $account = new Account();
        $profile = new Profile();
        if ($account->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post())) {
            $account->role = 2;
            $account->status = 1;
            if($account->save()){
                $update = Account::findOne(['email'=>$account->email]);
                $update->password = md5($account->password);
                $update->passwordrepeat = md5($account->passwordrepeat);
                $update->save();
                $profile->idaccount = $account->idaccount;
                if($profile->save()){
                    return $this->redirect(['login']);
                }
            }
            $account->password='';
            $account->passwordrepeat='';
        }
        return $this->render('register',[
            'account'=>$account,
            'profile'=>$profile,
        ]);
    }

    public function actionLogin()
    {
        $this->layout = "@app/modules/admin/views/layouts/main-login";
        $session = Yii::$app->session;
        $session->open();
        
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['index']);
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $command = Yii::$app->db->createCommand();
            $command->update('account',
                ['lastlogin'=>date('Y-m-d H:i:s')],//update lastlogin
                ['email'=>$model->username])->execute();
            $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
            $session->set('username',$profile->name);
            return $this->redirect(['index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $session = Yii::$app->session;

        // destroys all data registered to a session.
        $session->destroy();
        // close a session
        $session->close();
        return $this->redirect(['login']);
    }
}

modules/admin/controllers/FoodController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Food;
use app\models\Foodcat;
use app\models\Foodtype;
use app\modules\admin\models\UploadImage;
use yii\web\UploadedFile;
use yii\data\Pagination;
use yii\data\ActiveDataProvider;

class FoodController extends \yii\web\Controller
{
    private function Session(){
        return Yii::$app->session; // start session
    }
    private function Pagesize(){
        return 10; //page size 10
    }
	public function init() 
	{
	    parent::init();
	}

    public function beforeAction($action)
    {
        // check if not login
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['default/login']);
        }
        return parent::beforeAction($action);
    }

	/* Food */
    public function actionIndex()
    {
        // model food for search filter
        $food = new Food();
        // query for active data reader
    	$query = Food::find()
            ->where(['lang'=>$this->session()->get('language')]);
        // check if get search filter
        if ($food->load(Yii::$app->request->get())) {
            
            if ($food->idfoodtype!='' && $food->idfoodcat!='') {
                $query->andWhere(['idfoodtype'=>$food->idfoodtype,'idfoodcat'=>$food->idfoodcat]);
            }
            if ($food->idfoodtype!='' && $food->idfoodcat=='') {
                $query->andWhere(['idfoodtype'=>$food->idfoodtype]);
            }
            if ($food->idfoodcat!='' && $food->idfoodtype=='') {
                $query->andWhere(['idfoodcat'=>$food->idfoodcat]);
            }
        }
        // model for filter category
    	$cat = Foodcat::find()
            ->where(['lang'=>$this->session()->get('language')])->all();
        // model for filter type
    	$type = Foodtype::find()
            ->where(['lang'=>$this->session()->get('language')])->all();
        // active data provider
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => $this->pagesize(),
            ],
        ]);

        return $this->render('index',['food'=>$food,'cat'=>$cat,'type'=>$type,'dataProvider'=>$dataProvider]);
    }
    public function actionFoodAdd()
    {
        // datetime now
    	$date = date('YmdHis');
        // new record model
    	$model = new Food();
        // model upload image
    	$upload = new UploadImage();
        // check if post data
        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $modelimage = $upload->uploadImg($model->image,$date,$filename,'img/admin/food/');
		        if ($modelimage==true) {
                    //save image
		            $model->image = $filename . $date . '.' . $upload->imageFile->extension;
		        }
            }
            //default language if empty
            if (empty($model->lang)) {
                // value default fr (french)
                $model->lang = 'fr';
                $model->country = 'FR';
            }
            // save model
            $model->save();
            // query food
            $query = Food::find()
                ->where(['lang'=>$this->session()->get('language')]);
            // count query
            $count = $query->count();
            // check modulus 
            if ($count % $pagesize == 0) {
                $max_page = ($count - $count % $pagesize) / $pagesize;
            }elseif($count % $pagesize > 0){
                $max_page = ($count - $count % $pagesize) / $pagesize + 1;
            }else{
                $max_page = ($count - $count % $pagesize) / $pagesize + 1;
            }
            // redirect function index
        	return $this->redirect(['index','page'=>$max_page]);
        }
        // model catergory
    	$cat = Foodcat::find()->all();
        // model type
    	$type = Foodtype::find()->all();
    	return $this->render('_form_food',['model'=>$model,'cat'=>$cat,'type'=>$type,'upload'=>$upload,'title'=>'Add Food']);
    }
    public function actionFoodUpdate($id)
    {
        // check if set id
        if (!isset($id)) {
            return $this->redirect(['index']);
        }
        // datetime now
    	$date = date('YmdHis');
        // find one model by id
    	$model = Food::findOne($id);
        // model upload image
    	$upload = new UploadImage();
        //check if post data
    	if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $modelimage = $upload->uploadImg($model->image,$date,$filename,'img/admin/food/');
		        if ($modelimage==true) {
                    //rename image
		            $model->image = $filename . $date . '.' . $upload->imageFile->extension;
		        }
            }else{
                //no rename image
            	$model->image = $model->image;
            }
            $model->save();
        	return $this->redirect(['index']);
        }
        // model catergory
        $cat = Foodcat::find()->all();
        // model type
        $type = Foodtype::find()->all();
    	return $this->render('_form_food',['model'=>$model,'cat'=>$cat,'type'=>$type,'upload'=>$upload,'title'=>'Update Food']);
    }
    public function actionFoodDelete($id)
    {
        // model find one by id
    	$model = Food::findOne($id);
        // check if has image name
        if(!empty($model->image)){
            // unlink or delete file
            UploadImage::unLinkImage(Yii::$app->basePath . '/web/img/admin/food/' . $model->image);
        }
    	// delete model
        $model->delete();
    	return $this->redirect(['index']);
    }

    /* Food Category*/
    public function actionFoodCat()
    {
        // new model
        $model = new Foodcat();
        // check if post data
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
        }
        // model for data provider
    	$condition = Foodcat::find()
    		->where(['lang'=>$this->session()->get('language')]);
        // active data provider
        $dataProvider = new ActiveDataProvider([
            'query' => $condition,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
    	return $this->render('food-cat',['dataProvider'=>$dataProvider,'model'=>$model]);
    }
    public function actionFoodCatUpdate($id)
    {
    	$model = Foodcat::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['food-cat']);
        }
    	return $this->render('_form_food-cat',['model'=>$model]);
    }
    public function actionFoodCatDelete($id)
    {
        // model find one by id
    	$models = Foodcat::findOne($id);
        // delete model
    	$models->delete();
    	return $this->redirect(['food-cat']);
    }
    /* Food Type*/
    public function actionFoodType()
    {
        // new model
    	$model = new Foodtype();
        // check if post data
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
        }
        // find model
        $condition = Foodtype::find()
            ->where(['lang'=>$this->session()->get('language')]);
        // active data provider
        $dataProvider = new ActiveDataProvider([
            'query' => $condition,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
    	return $this->render('food-type',['model'=>$model,'dataProvider'=>$dataProvider]);
    }
    public function actionFoodTypeUpdate($id)
    {
        // model find one by id
        $model = Foodtype::findOne($id);
        // check if post data
    	if ($model->load(Yii::$app->request->post())) {
	    	$model->save();
    		
    		return $this->redirect(['food-type']);
    	}
    	return $this->render('_form_food-type',['model'=>$model]);
    }
    public function actionFoodTypeDelete($id)
    {
        // model find one by id
    	$models = Foodtype::findOne($id);
    	// delete model
    	$models->delete();
    	return $this->redirect(['food-type']);
    }

}

modules/admin/views/food/_form_food-cat.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = "Update Food Category";
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to([''])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<?= Url::to(['food/food-cat'])?>">Food Categories</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Update Food Category</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <?php $form = ActiveForm::begin([]) ?>
                <div class="box-body">
                  <?= $form->field($model, 'idfoodcat')->textInput(['readonly'=>true]) ?>
                  <?= $form->field($model, 'name') ?>
                  <?= $form->field($model, 'lang')->hiddenInput()->label(false) ?>
                </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <?= Html::a(Html::button('Cancel',['class'=>'btn btn-default']),['food/food-cat'])?>
                <?= Html::submitButton('Submit',['class'=>'btn btn-primary'])?>
              </div>
            <?php ActiveForm::end() ?>
          </div>
          <!-- /.box -->
        </div>
      </div>

</section>
<!-- /.content -->

modules/admin/views/food/_form_food-type.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = "Update Food Type";
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to(['default/index'])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<?= Url::to(['food/food-type'])?>">Food Type</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <!-- form start -->
            <?php $form = ActiveForm::begin([]) ?>
                <div class="box-body">
                  <?= $form->field($model, 'idfoodtype')->textInput(['readonly'=>true]) ?>
                  <?= $form->field($model, 'name') ?>
                  <?= $form->field($model, 'lang')->hiddenInput()->label(false) ?>
                </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <?= Html::a(Html::button('Cancel',['class'=>'btn btn-default']),['food/food-type'])?>
                <?= Html::submitButton('Submit',['class'=>'btn btn-primary'])?>
              </div>
            <?php ActiveForm::end() ?>
          </div>
          <!-- /.box -->
        </div>
      </div>

</section>
<!-- /.content -->

modules/admin/views/food/_form_food.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;
use app\helpers\ModuleHelper;
$this->title = $title;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to(['default/index'])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<?= Url::to(['food/index'])?>">Food</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">
        <!-- left column -->
        <div class="col-md-12">
          <!-- general form elements -->
          <div class="box box-primary">
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]) ?>
              <div class="box-body">
                <div class="col-md-6">
                <?= $form->field($model, 'idfoodtype')->dropdownList(ArrayHelper::map($type,'idfoodtype','name'),
                      ['prompt'=>'Select Type']) ?>
                <?= $form->field($model, 'idfoodcat')->dropdownList(ArrayHelper::map($cat,'idfoodcat','name'),
                      ['prompt'=>'Select Category']) ?>
                <?= $form->field($model, 'method')->dropdownList(ModuleHelper::getMethodList(),
                      ['prompt'=>'Select Method']
                  ) ?>
                <?= $form->field($model, 'phase')->dropdownList(ModuleHelper::getPhaseList(),
                      ['prompt'=>'Select Phase']
                  ) ?>
                <?= $form->field($model, 'idfood') ?>
                <?= $form->field($model, 'name') ?>
                </div>
                <div class="col-md-6">
                <?= $form->field($upload, 'imageFile')->fileInput(['accept' => 'image/jpg,image/png','class'=>'form-control']) ?>
                <?= $form->field($model, 'desc')->textArea() ?>
                <?= $form->field($model, 'lang')->dropdownList([
                          'fr' => 'French', 
                          'en' => 'English',
                          'es' => 'Spanish',
                          'it' => 'Italian',
                          'tr' => 'Turkish',
                          'pr' => 'Portuguese',
                          'ru' => 'Russian',
                          'cn' => 'Chinese',
                      ],
                      ['prompt'=>'Select Language','onchange'=>'$("input#food-country").val($(this).val().toUpperCase())']
                  ) ?>
                <?= $form->field($model, 'country')->hiddenInput()->label(false) ?>
                </div>
              </div>
              <div class="box-footer">
                <a href="<?= Url::to(['food/index'])?>">
                <?= Html::a(Html::button('Cancel',['class'=>'btn btn-default']),['food/index'])?>
                <?= Html::submitButton('Save',['class'=>'btn btn-primary'])?>
              </div>
            <?php ActiveForm::end() ?>
          <!-- /.box -->
        </div>
      </div>
</section>
<!-- /.content -->

modules/admin/views/food/_form_modal_cat.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
$session = Yii::$app->session;
?>
<div id="modal-add" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Modal Header</h4>
		</div>
	    <?php $form = ActiveForm::begin([]) ?>
		<div class="modal-body">
	      <?= $form->field($model, 'idfoodcat') ?>
	      <?= $form->field($model, 'name') ?>
	      <?= $form->field($model, 'lang')->hiddenInput(['value'=>$session->get('language')])->label(false) ?>
	      <?= Html::button('Cancel',['class'=>'btn btn-default','data-dismiss'=>'modal'])?>
	      <?= Html::submitButton('Submit',['class'=>'btn btn-primary'])?>
    	</div>
      	<div class="modal-footer">
		      <?= Html::button('Cancel',['class'=>'btn btn-default','data-dismiss'=>'modal'])?>
		      <?= Html::submitButton('Submit',['class'=>'btn btn-primary'])?>
      	</div>
	    <?php ActiveForm::end() ?>
    </div>

  </div>
</div>

modules/admin/views/food/_form_modal_type.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\Modal;
use yii\widgets\ActiveForm;
$session = Yii::$app->session;
?>
<div id="modal-add" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">&times;</button>
			<h4 class="modal-title">Modal Header</h4>
		</div>
	    <?php $form = ActiveForm::begin([]) ?>
		<div class="modal-body">

		      <?= $form->field($model, 'idfoodtype') ?>
		      <?= $form->field($model, 'name') ?>
		      <?= $form->field($model, 'lang')->hiddenInput(['value'=>$session->get('language')])->label(false) ?>

		</div>
      	<div class="modal-footer">
		      <?= Html::button('Cancel',['class'=>'btn btn-default','data-dismiss'=>'modal'])?>
		      <?= Html::submitButton('Submit',['class'=>'btn btn-primary'])?>
      	</div>
	    <?php ActiveForm::end() ?>
    </div>

  </div>
</div>

modules/admin/views/food/food-cat.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = "Food Category";
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to([''])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="v2-food-category">
	    <div class="row">
	        <div class="col-md-12">
	          <div class="box">
        		<div class="box-header">
	            	<?= Html::button('Add',['class'=>'btn btn-primary','data-toggle'=>'modal','data-target'=>'#modal-add'])?>
        		</div>
	            <!-- /.box-header -->
	            <div class="box-body">
	            	<?= GridView::widget([
					    'dataProvider' => $dataProvider,
					    'columns' => [
        					['class' => 'yii\grid\SerialColumn'],
        					'name',
        					['class' => 'yii\grid\ActionColumn',
        						'template'=>'{update}{delete}',
        						'buttons'=>[
                              		'update' => function ($url, $model) {
        							$url = Url::to(['food/food-cat-update','id'=>$model->idfoodcat]);	
									return Html::a('<span class="badge bg-blue"><span class="glyphicon glyphicon-pencil"></span></span>', $url, [
										'title' => Yii::t('yii', 'Update'),
									]);                                
                              		},
                              		'delete' => function ($url, $model) {	
        							$url = Url::to(['food/food-cat-delete','id'=>$model->idfoodcat]);	
									return Html::a('<span class="badge bg-red"><span class="glyphicon glyphicon-trash"></span></span>', $url, [
										'title' => Yii::t('yii', 'Delete'),
										'onclick'=>'return confirm(\'Are you sure you want to delete this data?\')'
									]);                                
                              		},
                          		]
                      		],
        				]
					]);?>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>

	  <?= $this->render('_form_modal_cat',['model'=>$model]);?>
	  
	</div>

</section>
<!-- /.content -->

modules/admin/views/food/food-type.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

$this->title = "Food Type";
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to([''])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
	<div class="v2-food-type">
		<div class="row">
	        <div class="col-md-12">
	          <div class="box">
        		<div class="box-header">
	            	<?= Html::button('Add',['class'=>'btn btn-primary','data-toggle'=>'modal','data-target'=>'#modal-add'])?>
        		</div>
	            <!-- /.box-header -->
	            <div class="box-body">
	            	<?= GridView::widget([
					    'dataProvider' => $dataProvider,
					    'columns' => [
        					['class' => 'yii\grid\SerialColumn'],
        					'name',
        					['class' => 'yii\grid\ActionColumn',
        						'template'=>'{update}{delete}',
        						'buttons'=>[
                              		'update' => function ($url, $model) {
        							$url = Url::to(['food/food-type-update','id'=>$model->idfoodtype]);	
									return Html::a('<span class="badge bg-blue"><span class="glyphicon glyphicon-pencil"></span></span>', $url, [
										'title' => Yii::t('yii', 'Update'),
									]);                                
                              		},
                              		'delete' => function ($url, $model) {	
        							$url = Url::to(['food/food-type-delete','id'=>$model->idfoodtype]);	
									return Html::a('<span class="badge bg-red"><span class="glyphicon glyphicon-trash"></span></span>', $url, [
										'title' => Yii::t('yii', 'Delete'),
										'onclick'=>'return confirm(\'Are you sure you want to delete this data?\')'
									]);                                
                              		},
                          		]
                      		],
        				]
					]);?>
	            </div>
	            <!-- /.box-body -->
	          </div>
	          <!-- /.box -->
	      </div>
	  </div>

	  <?= $this->render('_form_modal_type',['model'=>$model]);?>
	</div>

</section>
<!-- /.content -->

modules/admin/views/food/index.php
<?php
/* @var $this yii\web\View */
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\widgets\LinkPager;
use yii\widgets\ActiveForm;
use yii\grid\GridView;

use app\models\Food;

$this->title = "List Food";
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to(['default/index'])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">

<div class="row">
    <div class="col-md-12">
      <div class="box">
        <div class="box-header">
          <?php $form = ActiveForm::begin(['id'=>'form-search','method'=>'get','options' => ['enctype' => 'multipart/form-data']]) ?>
            <div class="col-md-6">
              <?= $form->field($food, 'idfoodtype')->dropdownList(ArrayHelper::map($type,'idfoodtype','name'),
                    ['prompt'=>'Select Type','onchange'=>'$("#form-search").submit()']) ?>
            </div>
            <div class="col-md-6">
              <?= $form->field($food, 'idfoodcat')->dropdownList(ArrayHelper::map($cat,'idfoodcat','name'),
                    ['prompt'=>'Select Category','onchange'=>'$("#form-search").submit()']) ?>
            </div>
          <?php ActiveForm::end() ?>
          <div class="col-md-12">
            <?= Html::a(Html::button('Add',['class'=>'btn btn-primary']),['food/food-add'])?>
          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body" style="overflow-x: auto;">
          <?= GridView::widget([
              'dataProvider' => $dataProvider,
              'columns' => [
                  ['class' => 'yii\grid\SerialColumn'],
                  'name',
                  [
                    'attribute'=>'method',
                    'value'=> function($model){
                      return Food::getMethod($model->method);
                    },
                  ],
                  [
                    'attribute'=>'phase',
                    'value'=> function($model){
                      return Food::getPhase($model->phase);
                    },
                  ],
                  [
                    'attribute'=>'image',
                    'format'=>'html',
                    'value'=> function($model){
                      return Html::img('@web/img/admin/food/'.$model->image, ['alt' => 'My logo','style'=>'width:125px']);
                    },
                  ],
                  'desc',
                  ['class' => 'yii\grid\ActionColumn',
                    'template'=>'{update} {delete}',
                    'buttons'=>[
                                  'update' => function ($url, $model) {
                      $url = Url::to(['food/food-update','id'=>$model->idfood]); 
                  return Html::a('<span class="badge bg-blue"><span class="glyphicon glyphicon-pencil"></span></span>', $url, [
                    'title' => Yii::t('yii', 'Update'),
                  ]);                                
                                  },
                                  'delete' => function ($url, $model) { 
                      $url = Url::to(['food/food-delete','id'=>$model->idfood]); 
                  return Html::a('<span class="badge bg-red"><span class="glyphicon glyphicon-trash"></span></span>', $url, [
                    'title' => Yii::t('yii', 'Delete'),
                    'onclick'=>'return confirm(\'Are you sure you want to delete this data?\')'
                  ]);                                
                                  },
                              ]
                  ],
                ]
          ]);?>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
  </div>
</div>

</section>
<!-- /.content -->