modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\User;
use app\models\Account;
use app\models\Profile;
use app\modules\admin\models\Language;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
	public function init() {

	    parent::init();
	    // $this->layout = '@app/modules/admin/views/layouts/main';
	    // custom initialization code goes here
	}

    public function actionError()
    {
        return $this->render('error');
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        if (!$session->has('language')) {
            $session->set('language', 'fr');
        }
        
        $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
        if (!empty($profile)) {
            $session->set('username',$profile->name);
            $name = $profile->name;
        }else{
            $name = '';
        }
        
        return $this->render('index',[
            'lang'=>$session->get('language'),
            'name'=>$name,
        ]);
    }

    public function actionLanguage()
    {
        $language = new Language();
        $session = Yii::$app->session;
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $alert='';
        if ($language->load(Yii::$app->request->post())) {
            $session->set('language', $language->lang);
            $alert = '<div class="alert alert-success alert-dismissible fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><h4><i class="icon fa fa-check"></i> Success!</h4>Success to Change Language.</div>';
        }
        if ($language->lang) {
            $session->set('language', $language->lang);
        }
        return $this->render('language',[
            'alert'=>$alert,
            'language'=>$language,]);
    }

    public function actionRegister()
    {
        $this->layout = "@app/modules/admin/views/layouts/main-login";

        $account = new Account();
        $profile = new Profile();
        if ($account->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post())) {
            $account->role = 2;
            $account->status = 1;
            if($account->save()){
                $update = Account::findOne(['email'=>$account->email]);
                $update->password = md5($account->password);
                $update->passwordrepeat = md5($account->passwordrepeat);
                $update->save();
                $profile->idaccount = $account->idaccount;
                if($profile->save()){
                    return $this->redirect(['login']);
                }
            }
            $account->password='';
            $account->passwordrepeat='';
        }
        return $this->render('register',[
            'account'=>$account,
            'profile'=>$profile,
        ]);
    }

    public function actionLogin()
    {
        $this->layout = "@app/modules/admin/views/layouts/main-login";
        $session = Yii::$app->session;
        $session->open();
        
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['index']);
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $command = Yii::$app->db->createCommand();
            $command->update('account',
                ['lastlogin'=>date('Y-m-d H:i:s')],//update lastlogin
                ['email'=>$model->username])->execute();
            $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
            $session->set('username',$profile->name);
            return $this->redirect(['index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $session = Yii::$app->session;

        // destroys all data registered to a session.
        $session->destroy();
        // close a session
        $session->close();
        return $this->redirect(['login']);
    }
}

modules/admin/views/default/error.php
<?php
use yii\helpers\Url;

$this->title = "404 Error Page";
?>
    <!-- Content Header (Page header) -->
    <section class="content-header">
      
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">404 error</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="error-page">
        <!-- <h2 class="headline text-yellow"> 404</h2> -->

        <div class="error-content">
          <h3><i class="fa fa-warning text-yellow"></i> Oops! Page not found.</h3>

          <p>
            We could not find the page you were looking for.
            Meanwhile, you may <a href="<?= Url::to(['default/index'])?>">return to dashboard</a> or try using others menu.
          </p>

          
        </div>
        <!-- /.error-content -->
      </div>
      <!-- /.error-page -->
    </section>
    <!-- /.content -->

modules/admin/views/default/index.php
<?php
use yii\helpers\Url;

$this->title = "Dashboard";
$session = Yii::$app->session;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to([''])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="v2-default-index">
    <h2>Hai, <?= $name;?></h2>
    <h1>Welcome back to Admin Panel</h1>
</div>

</section>
<!-- /.content -->

modules/admin/views/default/language.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = "Language";
$session = Yii::$app->session;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to([''])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>

<!-- Main content -->
<section class="content">
<div class="row">
  <!-- left column -->
  <div class="col-md-12">
    <!-- general form elements -->
    <div class="box box-primary">
      <div class="box-header with-border">
        <h3 class="box-title">Change Language</h3>
      </div>
      <!-- /.box-header -->
      <!-- form start -->
      <?php $form = ActiveForm::begin(['id'=>'form-lang','options'=>['role'=>'form']]) ?>
        <div class="box-body">
          <?= $form->field($language, 'lang', [
              'options' => ['class' => 'form-group'],
          ])->radioList([
                'fr' => Html::img('@web/img/lang/lang_fr.png',['style'=>'width:25px']).' French', 
                'en' => Html::img('@web/img/lang/lang_en.png',['style'=>'width:25px']).' English',
                'es' => Html::img('@web/img/lang/lang_es.png',['style'=>'width:25px']).' Spanish',
                'it' => Html::img('@web/img/lang/lang_it.png',['style'=>'width:25px']).' Italian',
                'tr' => Html::img('@web/img/lang/lang_tr.png',['style'=>'width:25px']).' Turkish',
                'pr' => Html::img('@web/img/lang/lang_pr.png',['style'=>'width:25px']).' Portuguese',
                'ru' => Html::img('@web/img/lang/lang_ru.png',['style'=>'width:25px']).' Russian',
                'de' => Html::img('@web/img/lang/lang_de.png',['style'=>'width:25px']).' Germany',
                'cn' => Html::img('@web/img/lang/lang_cn.png',['style'=>'width:25px']).' Chinese',
            ],['value'=>$session->get('language'),'encode'=>false,'class'=>'radio'])->label(false)?>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
          <?= Html::submitButton('Save Changes',['class'=>'btn btn-primary'])?>
        </div>
      <?php ActiveForm::end() ?>
    </div>
    <!-- /.box -->
    <div id="alerts">
    <?= $alert;?></div>
  </div>
</div>

</section>
<!-- /.content -->

modules/admin/views/default/login.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap\ActiveForm;

$this->title = "Login";
?>

<div class="login-box">
  <div class="login-logo">
    <b>Admin Panel</b>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

      <?php $form = ActiveForm::begin([
        'id' => 'login-form',
      ]); ?>
        <?= $form->field($model, 'username', [
              'options' => ['class' => 'form-group has-feedback'],
              'inputTemplate' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
          ])->textInput(['autofocus' => true,'placeholder'=>'Email'])->label(false) ?>
        <?= $form->field($model, 'password', [
              'options' => ['class' => 'form-group has-feedback'],
              'inputTemplate' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
          ])->passwordInput(['placeholder'=>'Password'])->label(false) ?>
        <div class="row">
          <div class="col-xs-8">
            <div class="checkbox icheck">
              <label>
            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "{input} {label}\n<div class=\"col-lg-12\">{error}</div>",
            ]) ?>
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-xs-4">
            <?= Html::submitButton('Sign In',['class'=>'btn btn-primary btn-block btn-flat'])?>
          </div>
        <!-- /.col -->
        </div>
    <?php ActiveForm::end(); ?>
    <?= Html::a('I forgot my password',['#'])?><br>
    <?= Html::a('Register a new membership',['default/register'],['class'=>'text-center'])?>
  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->

modules/admin/views/default/register.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = "Register";
?>

<div class="login-box">
  <div class="login-logo">
    <b>Admin Panel</b>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Register a new membership</p>

      <?php $form = ActiveForm::begin([
        'id' => 'register-form',
    ]); ?>
      <?= $form->field($profile, 'fullname', [
              'options' => ['class' => 'form-group has-feedback'],
              'template' => "{input}<span class='glyphicon glyphicon-user form-control-feedback'></span>"
          ])->textInput(['autofocus' => true,'placeholder'=>'Fullname'])->label(false) ?>
      <?= $form->field($profile, 'name', [
              'options' => ['class' => 'form-group has-feedback'],
              'template' => "{input}<span class='glyphicon glyphicon-user form-control-feedback'></span>"
          ])->textInput(['placeholder'=>'Name'])->label(false) ?>
      <?= $form->field($account, 'email', [
              'options' => ['class' => 'form-group has-feedback'],
              'template' => "{input}<span class='glyphicon glyphicon-envelope form-control-feedback'></span>"
          ])->textInput(['placeholder'=>'Email'])->label(false) ?>
      <?= $form->field($account, 'password', [
              'options' => ['class' => 'form-group has-feedback'],
              'template' => "{input}<span class='glyphicon glyphicon-lock form-control-feedback'></span>"
          ])->passwordInput(['placeholder'=>'Password'])->label(false) ?>
      <?= $form->field($account, 'passwordrepeat', [
              'options' => ['class' => 'form-group has-feedback'],
              'template' => "{input}<span class='glyphicon glyphicon-log-in form-control-feedback'></span>"
          ])->passwordInput(['placeholder'=>'Password Repeat'])->label(false) ?>
      <?= $form->field($profile, 'gender', [
              'options' => ['class' => 'form-group has-feedback'],
              'template' => "{input}",
          ])->radioList([
              'M' => 'Male', 
              'F' => 'Female'
          ])->label(false) ?>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> I agree to the <a href="#">terms</a>
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <?= Html::submitButton('Register',['class'=>'btn btn-primary btn-block btn-flat','disabled'])?>
        </div>
        <!-- /.col -->
      </div>
    <?php ActiveForm::end(); ?>
    <?= Html::a('I already have a membership',['default/login'],['class'=>'text-center'])?>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->