modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\User;
use app\models\Account;
use app\models\Profile;
use app\modules\admin\models\Language;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
	public function init() {

	    parent::init();
	    // $this->layout = '@app/modules/admin/views/layouts/main';
	    // custom initialization code goes here
	}

    public function actionError()
    {
        return $this->render('error');
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        if (!$session->has('language')) {
            $session->set('language', 'fr');
        }
        
        $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
        if (!empty($profile)) {
            $session->set('username',$profile->name);
            $name = $profile->name;
        }else{
            $name = '';
        }
        
        return $this->render('index',[
            'lang'=>$session->get('language'),
            'name'=>$name,
        ]);
    }

    public function actionLanguage()
    {
        $language = new Language();
        $session = Yii::$app->session;
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $alert='';
        if ($language->load(Yii::$app->request->post())) {
            $session->set('language', $language->lang);
            $alert = '<div class="alert alert-success alert-dismissible fade in"><button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button><h4><i class="icon fa fa-check"></i> Success!</h4>Success to Change Language.</div>';
        }
        if ($language->lang) {
            $session->set('language', $language->lang);
        }
        return $this->render('language',[
            'alert'=>$alert,
            'language'=>$language,]);
    }

    public function actionRegister()
    {
        $this->layout = "@app/modules/admin/views/layouts/main-login";

        $account = new Account();
        $profile = new Profile();
        if ($account->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post())) {
            $account->role = 2;
            $account->status = 1;
            if($account->save()){
                $update = Account::findOne(['email'=>$account->email]);
                $update->password = md5($account->password);
                $update->passwordrepeat = md5($account->passwordrepeat);
                $update->save();
                $profile->idaccount = $account->idaccount;
                if($profile->save()){
                    return $this->redirect(['login']);
                }
            }
            $account->password='';
            $account->passwordrepeat='';
        }
        return $this->render('register',[
            'account'=>$account,
            'profile'=>$profile,
        ]);
    }

    public function actionLogin()
    {
        $this->layout = "@app/modules/admin/views/layouts/main-login";
        $session = Yii::$app->session;
        $session->open();
        
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['index']);
        }
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            $command = Yii::$app->db->createCommand();
            $command->update('account',
                ['lastlogin'=>date('Y-m-d H:i:s')],//update lastlogin
                ['email'=>$model->username])->execute();
            $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
            $session->set('username',$profile->name);
            return $this->redirect(['index']);
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        $session = Yii::$app->session;

        // destroys all data registered to a session.
        $session->destroy();
        // close a session
        $session->close();
        return $this->redirect(['login']);
    }
}

modules/admin/controllers/TestimoniController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Testimoni;
use app\modules\admin\models\UploadImage;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;

/**
 * TestimoniController implements the CRUD actions for Testimoni model.
 */
class TestimoniController extends Controller
{
    private function Session(){
        return Yii::$app->session; // start session
    }
    private function Pagesize(){
        return 10; //page size 10
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['default/login']);
        }
        return parent::beforeAction($action);
    }
    /**
     * Lists all Testimoni models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = Testimoni::find()->where(['lang'=>$this->session()->get('language')]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
             'pageSize' => $this->pagesize(),
            ],
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Testimoni model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        // return $this->render('view', [
        //     'model' => $this->findModel($id),
        // ]);
        return $this->redirect(['index']);
    }

    /**
     * Creates a new Testimoni model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $date = date('YmdHis');
        $model = new Testimoni();
        $upload = new UploadImage();

        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $modelimage = $upload->uploadImg($model->image,$date,$filename,'img/testimoni/');
                if ($modelimage==true) {
                    //save image
                    $model->image = $filename . $date . '.' . $upload->imageFile->extension;
                }
            }else{
                $model->image = "-";
            }
            
            $model->lang = $this->session()->get('language');
            $model->dateinput = $date;
            $model->save();
            // return $this->redirect(['view', 'id' => $model->idtestimoni]);
            return $this->redirect(['index']);
        }

        return $this->render('create', [
            'model' => $model,
            'upload' => $upload,
        ]);
    }

    /**
     * Updates an existing Testimoni model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $date = date('YmdHis');
        $model = $this->findModel($id);
        $upload = new UploadImage();

        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $modelimage = $upload->uploadImg($model->image,$date,$filename,'img/testimoni/');
                if ($modelimage==true) {
                    //save image
                    $model->image = $filename . $date . '.' . $upload->imageFile->extension;
                }
            }else{
                $model->image = $model->image;
            }
            $model->dateupdate = $date;
            $model->save();
            // return $this->redirect(['view', 'id' => $model->idtestimoni]);
            return $this->redirect(['index']);
        }

        return $this->render('update', [
            'model' => $model,
            'upload' => $upload,
        ]);
    }

    /**
     * Deletes an existing Testimoni model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = Testimoni::findOne($id);
        UploadImage::unLinkImage(Yii::$app->basePath . '/web/img/testimoni/'.$model->image);
        $model->delete();
        //$this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Testimoni model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Testimoni the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Testimoni::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

modules/admin/views/testimoni/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use app\helpers\ModuleHelper;

/* @var $this yii\web\View */
/* @var $model app\models\Testimoni */
/* @var $form yii\widgets\ActiveForm */
?>
<?php $this->registerCssFile("@web/vender/AdminLTE/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css")?>

<div class="testimoni-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'method')->dropdownList(ModuleHelper::getMethodList(),['prompt'=>'Select Method']) ?>

    <?= $form->field($model, 'phase')->dropdownList(ModuleHelper::getPhaseList(),['prompt'=>'Select Phase']) ?>

    <?= $form->field($upload, 'imageFile')->fileInput(['accept' => 'image/jpg,image/png','class'=>'form-control']) ?>

    <?= $form->field($model, 'desc')->textarea(['rows' => 6,'class'=>'textarea form-control','Place some text here']) ?>

    <?= $form->field($model, 'age')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'wstart')->textInput(['maxlength' => true,'type' => 'number'])->label('First Weight (kg)') ?>

    <?= $form->field($model, 'wlast')->textInput(['maxlength' => true,'type' => 'number'])->label('Last Weight (kg)') ?>

    <div class="form-group">
        <?= Html::a('Cancel',['index'], ['class' => 'btn btn-default']) ?>
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php $this->registerJsFile("@web/vender/AdminLTE/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js")?>
<script>
  $(function () {
    //bootstrap WYSIHTML5 - text editor
    $('.textarea').wysihtml5()
  })
</script>

modules/admin/views/testimoni/create.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Testimoni */

$this->title = 'Create Testimoni';
$this->params['breadcrumbs'][] = ['label' => 'Testimonis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to(['default/index'])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<?= Url::to(['testimoni/index'])?>">Testimoni</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>
<!-- Main content -->
<section class="content">

<div class="row">
    <div class="col-md-12">
        <div class="box">
			<div class="testimoni-create">

			<?= $this->render('_form', [
			    'model' => $model,
          'upload' => $upload,
			]) ?>

			</div>
		</div>
	</div>
</div>

modules/admin/views/testimoni/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;

use app\models\Food;
$session = Yii::$app->session;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Testimoni';
$this->params['breadcrumbs'][] = $this->title;
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to(['default/index'])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>
<!-- Main content -->
<section class="content">

<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="testimoni-index">

                <p>
                    <?= Html::a('Create Testimoni', ['create'], ['class' => 'btn btn-success']) ?>
                </p>


                <?= GridView::widget([
                    'dataProvider' => $dataProvider,
                    'columns' => [
                        ['class' => 'yii\grid\SerialColumn'],

                        //'idtestimoni',
                        [
                            'attribute'=>'method',
                            'value'=>function($model){
                                return Food::getMethod($model->method);
                            }
                        ],
                        [
                            'attribute'=>'phase',
                            'value'=>function($model){
                                return Food::getPhase($model->phase);
                            }
                        ],
                        [ 
                            'attribute'=>'image',
                            'format'=>'html',
                            'value'=>function($model){
                                return Html::img('@web/img/testimoni/'.$model->image, ['alt' => 'My logo','style'=>'width:125px']);
                            }
                        ],
                        'desc:html',
                        //'lang',
                        //'age',
                        //'dateinput',

                        ['class' => 'yii\grid\ActionColumn','template'=>'{update} {delete}','buttons'=>[
                                  'update' => function ($url, $model) {
                      $url = Url::to(['update','id'=>$model->idtestimoni]); 
                  return Html::a('<span class="badge bg-blue"><span class="glyphicon glyphicon-pencil"></span></span>', $url, [
                    'title' => Yii::t('yii', 'Update'),
                  ]);                                
                                  },
                                  'delete' => function ($url, $model) { 
                      $url = Url::to(['delete','id'=>$model->idtestimoni]); 
                  return Html::a('<span class="badge bg-red"><span class="glyphicon glyphicon-trash"></span></span>', $url, [
                    'title' => Yii::t('yii', 'Delete'),
                    'onclick'=>'return confirm(\'Are you sure you want to delete this data?\')'
                  ]);                                
                                  },
                              ]],
                    ],
                ]); ?>


            </div>
        </div>
    </div>
</div>

modules/admin/views/testimoni/update.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Testimoni */

$this->title = 'Update Testimoni: ';
$this->params['breadcrumbs'][] = ['label' => 'Testimonis', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->idtestimoni, 'url' => ['view', 'id' => $model->idtestimoni]];
$this->params['breadcrumbs'][] = 'Update';
?>
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>
    <?= $this->title;?>
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="<?= Url::to(['default/index'])?>"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="<?= Url::to(['testimoni/index'])?>">Testimoni</a></li>
    <li class="active"><?= $this->title;?></li>
  </ol>
</section>
<!-- Main content -->
<section class="content">

<div class="row">
    <div class="col-md-12">
        <div class="box">
			<div class="testimoni-update">

			    <?= $this->render('_form', [
			        'model' => $model,
			        'upload' => $upload,
			    ]) ?>

			</div>
		</div>
	</div>
</div>

modules/admin/views/testimoni/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Testimoni */

$this->title = $model->idtestimoni;
$this->params['breadcrumbs'][] = ['label' => 'Testimonis', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="testimoni-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->idtestimoni], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->idtestimoni], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'idtestimoni',
            'method',
            'phase',
            'image',
            'desc:ntext',
            'lang',
            'age',
            'dateinput',
        ],
    ]) ?>

</div>