modules/admin/controllers/AccountController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Account;
use app\models\User;
use app\models\Profile;
use app\modules\admin\models\UploadImage;
use yii\web\UploadedFile;
use yii\data\ActiveDataProvider;

class AccountController extends \yii\web\Controller
{
	public function init() 
	{
	    parent::init();
	    $this->layout = '@app/modules/admin/views/layouts/main';
	    // custom initialization code goes here
	}

    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['default/login']);
        }
        return parent::beforeAction($action);
    }
    public function actionIndex()
    {
        $pagesize=10;
        $role = Account::findOne(Yii::$app->user->id);
        if ($role->role!=1) {
            return $this->redirect(['default/error']);
        }
        $query = Account::find();
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => $pagesize,
            ],
        ]);
        return $this->render('index',['dataProvider'=>$dataProvider]);
    }
    public function actionAdd()
    {
    	$model = new Account();
        $profile = new Profile();
    	if ($model->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post())) {
    		if($model->save()){
                $account = Account::findOne(['email'=>$model->email]);
                $account->password = md5($account->password);
                $account->passwordrepeat = md5($account->passwordrepeat);
                $account->save();
                $profile->name = $profile->fullname;
                $profile->gender = 'M';
                $profile->idaccount = $model->idaccount;
                if($profile->save()){
                    return $this->redirect(['index']);
                }
    		}
    	}
    	return $this->render('_form',['model'=>$model,'profile'=>$profile,'title'=>'Add Account']);
    }
    public function actionUpdate($id)
    {
        $model = Account::findOne($id);
        $profile = Profile::findOne(['idaccount'=>$id]);
        if ($model->load(Yii::$app->request->post()) && $profile->load(Yii::$app->request->post())) {
            
            if($model->save()){
                $account = Account::findOne(['email'=>$model->email]);
                $account->password = md5($model->password);
                $account->passwordrepeat = md5($model->passwordrepeat);
                $account->save();
                $profile->name = $profile->fullname;
                $profile->gender = 'M';
                $profile->idaccount = $model->idaccount;
                if($profile->save()){
                    return $this->redirect(['index']);
                }
            }
        }
        return $this->render('_form',['model'=>$model,'profile'=>$profile,'title'=>'Update Account']);
    }
    public function actionDelete($id)
    {
        $profile = Profile::findOne(['idaccount'=>$id]);
        if (!empty($profile)) {
            if(!empty($profile->image))
            {
                UploadImage::unLinkImage(Yii::$app->basePath . '/web/img/admin/profile/' . $profile->image);
            }
            $profile->delete();
        }
        $model = Account::findOne($id);
        $model->delete(); 

    	return $this->redirect(['index']);
    }

    public function actionProfile()
    {
        $alert = '';
        $date = date('YmdHis');
        $profile = Profile::findOne(['idaccount'=>Yii::$app->user->id]);
        $upload = new UploadImage();
        if ($profile->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $profileimage = $upload->uploadImg($profile->image,$date,$filename,'img/admin/profile/');
                if ($profileimage==true) {
                    //rename image
                    $profile->image = $filename . $date . '.' . $upload->imageFile->extension;
                }
            }else{
                //no rename image
                $profile->image = $profile->image;
            }

            $datedob = date_create($profile->dob);
            $profile->dob = date_format($datedob,'Y-m-d');
            if($profile->save()){
                $alert = '<div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <h4><i class="icon fa fa-check"></i> Success!</h4>
                    Success to change profile.
                  </div>';
            }
        }

        return $this->render('profile',['profile'=>$profile,'upload'=>$upload,'alert'=>$alert]);
    }

    public function actionChangeStatus($id,$status)
    {
        $status = ($status=='true') ? 1 : 0;
        $command = Yii::$app->db->createCommand()
            ->update('account',['status'=>$status],['idaccount'=>$id]);
        $command->execute();
    }

}

modules/admin/controllers/FoodController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Food;
use app\models\Foodcat;
use app\models\Foodtype;
use app\modules\admin\models\UploadImage;
use yii\web\UploadedFile;
use yii\data\Pagination;
use yii\data\ActiveDataProvider;

class FoodController extends \yii\web\Controller
{
    private function Session(){
        return Yii::$app->session; // start session
    }
    private function Pagesize(){
        return 10; //page size 10
    }
	public function init() 
	{
	    parent::init();
	}

    public function beforeAction($action)
    {
        // check if not login
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['default/login']);
        }
        return parent::beforeAction($action);
    }

	/* Food */
    public function actionIndex()
    {
        // model food for search filter
        $food = new Food();
        // query for active data reader
    	$query = Food::find()
            ->where(['lang'=>$this->session()->get('language')]);
        // check if get search filter
        if ($food->load(Yii::$app->request->get())) {
            
            if ($food->idfoodtype!='' && $food->idfoodcat!='') {
                $query->andWhere(['idfoodtype'=>$food->idfoodtype,'idfoodcat'=>$food->idfoodcat]);
            }
            if ($food->idfoodtype!='' && $food->idfoodcat=='') {
                $query->andWhere(['idfoodtype'=>$food->idfoodtype]);
            }
            if ($food->idfoodcat!='' && $food->idfoodtype=='') {
                $query->andWhere(['idfoodcat'=>$food->idfoodcat]);
            }
        }
        // model for filter category
    	$cat = Foodcat::find()
            ->where(['lang'=>$this->session()->get('language')])->all();
        // model for filter type
    	$type = Foodtype::find()
            ->where(['lang'=>$this->session()->get('language')])->all();
        // active data provider
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => $this->pagesize(),
            ],
        ]);

        return $this->render('index',['food'=>$food,'cat'=>$cat,'type'=>$type,'dataProvider'=>$dataProvider]);
    }
    public function actionFoodAdd()
    {
        // datetime now
    	$date = date('YmdHis');
        // new record model
    	$model = new Food();
        // model upload image
    	$upload = new UploadImage();
        // check if post data
        if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $modelimage = $upload->uploadImg($model->image,$date,$filename,'img/admin/food/');
		        if ($modelimage==true) {
                    //save image
		            $model->image = $filename . $date . '.' . $upload->imageFile->extension;
		        }
            }
            //default language if empty
            if (empty($model->lang)) {
                // value default fr (french)
                $model->lang = 'fr';
                $model->country = 'FR';
            }
            // save model
            $model->save();
            // query food
            $query = Food::find()
                ->where(['lang'=>$this->session()->get('language')]);
            // count query
            $count = $query->count();
            // check modulus 
            if ($count % $pagesize == 0) {
                $max_page = ($count - $count % $pagesize) / $pagesize;
            }elseif($count % $pagesize > 0){
                $max_page = ($count - $count % $pagesize) / $pagesize + 1;
            }else{
                $max_page = ($count - $count % $pagesize) / $pagesize + 1;
            }
            // redirect function index
        	return $this->redirect(['index','page'=>$max_page]);
        }
        // model catergory
    	$cat = Foodcat::find()->all();
        // model type
    	$type = Foodtype::find()->all();
    	return $this->render('_form_food',['model'=>$model,'cat'=>$cat,'type'=>$type,'upload'=>$upload,'title'=>'Add Food']);
    }
    public function actionFoodUpdate($id)
    {
        // check if set id
        if (!isset($id)) {
            return $this->redirect(['index']);
        }
        // datetime now
    	$date = date('YmdHis');
        // find one model by id
    	$model = Food::findOne($id);
        // model upload image
    	$upload = new UploadImage();
        //check if post data
    	if ($model->load(Yii::$app->request->post())) {
            $upload->imageFile = UploadedFile::getInstance($upload, 'imageFile');
            //check if file not empty
            if(!empty($upload->imageFile) && $upload->imageFile->size !== 0) {
                //rename filename
                $filename = $upload->removeSpecialChar($upload->imageFile->baseName);
                //upload image
                $modelimage = $upload->uploadImg($model->image,$date,$filename,'img/admin/food/');
		        if ($modelimage==true) {
                    //rename image
		            $model->image = $filename . $date . '.' . $upload->imageFile->extension;
		        }
            }else{
                //no rename image
            	$model->image = $model->image;
            }
            $model->save();
        	return $this->redirect(['index']);
        }
        // model catergory
        $cat = Foodcat::find()->all();
        // model type
        $type = Foodtype::find()->all();
    	return $this->render('_form_food',['model'=>$model,'cat'=>$cat,'type'=>$type,'upload'=>$upload,'title'=>'Update Food']);
    }
    public function actionFoodDelete($id)
    {
        // model find one by id
    	$model = Food::findOne($id);
        // check if has image name
        if(!empty($model->image)){
            // unlink or delete file
            UploadImage::unLinkImage(Yii::$app->basePath . '/web/img/admin/food/' . $model->image);
        }
    	// delete model
        $model->delete();
    	return $this->redirect(['index']);
    }

    /* Food Category*/
    public function actionFoodCat()
    {
        // new model
        $model = new Foodcat();
        // check if post data
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
        }
        // model for data provider
    	$condition = Foodcat::find()
    		->where(['lang'=>$this->session()->get('language')]);
        // active data provider
        $dataProvider = new ActiveDataProvider([
            'query' => $condition,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
    	return $this->render('food-cat',['dataProvider'=>$dataProvider,'model'=>$model]);
    }
    public function actionFoodCatUpdate($id)
    {
    	$model = Foodcat::findOne($id);
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
            return $this->redirect(['food-cat']);
        }
    	return $this->render('_form_food-cat',['model'=>$model]);
    }
    public function actionFoodCatDelete($id)
    {
        // model find one by id
    	$models = Foodcat::findOne($id);
        // delete model
    	$models->delete();
    	return $this->redirect(['food-cat']);
    }
    /* Food Type*/
    public function actionFoodType()
    {
        // new model
    	$model = new Foodtype();
        // check if post data
        if ($model->load(Yii::$app->request->post())) {
            $model->save();
        }
        // find model
        $condition = Foodtype::find()
            ->where(['lang'=>$this->session()->get('language')]);
        // active data provider
        $dataProvider = new ActiveDataProvider([
            'query' => $condition,
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);
    	return $this->render('food-type',['model'=>$model,'dataProvider'=>$dataProvider]);
    }
    public function actionFoodTypeUpdate($id)
    {
        // model find one by id
        $model = Foodtype::findOne($id);
        // check if post data
    	if ($model->load(Yii::$app->request->post())) {
	    	$model->save();
    		
    		return $this->redirect(['food-type']);
    	}
    	return $this->render('_form_food-type',['model'=>$model]);
    }
    public function actionFoodTypeDelete($id)
    {
        // model find one by id
    	$models = Foodtype::findOne($id);
    	// delete model
    	$models->delete();
    	return $this->redirect(['food-type']);
    }

}

modules/admin/views/layouts/_control_sidebar.php
<aside class="control-sidebar control-sidebar-dark" style="display: none;">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-user bg-yellow"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Frodo Updated His Profile</h4>

                <p>New phone +1(800)555-1234</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-envelope-o bg-light-blue"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Nora Joined Mailing List</h4>

                <p>nora@example.com</p>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <i class="menu-icon fa fa-file-code-o bg-green"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Cron Job 254 Executed</h4>

                <p>Execution time 5 seconds</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="label label-danger pull-right">70%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Update Resume
                <span class="label label-success pull-right">95%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-success" style="width: 95%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Laravel Integration
                <span class="label label-warning pull-right">50%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-warning" style="width: 50%"></div>
              </div>
            </a>
          </li>
          <li>
            <a href="javascript:void(0)">
              <h4 class="control-sidebar-subheading">
                Back End Framework
                <span class="label label-primary pull-right">68%</span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-primary" style="width: 68%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Allow mail redirect
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Other sets of options are available
            </p>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Expose author name in posts
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Allow the user to show his name in blog posts
            </p>
          </div>
          <!-- /.form-group -->

          <h3 class="control-sidebar-heading">Chat Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Show me as online
              <input type="checkbox" class="pull-right" checked>
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Turn off notifications
              <input type="checkbox" class="pull-right">
            </label>
          </div>
          <!-- /.form-group -->

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Delete chat history
              <a href="javascript:void(0)" class="text-red pull-right"><i class="fa fa-trash-o"></i></a>
            </label>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>

modules/admin/views/layouts/_left_bar.php
<?php

use yii\helpers\Url;
use app\helpers\LinkHelper;
$session = Yii::$app->session;
?>
<section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?= Url::base()?>/vendor/AdminLTE/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?= ($session->get('username')) ? $session->get('username') : '["Username"]' ?></p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <!-- <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form> -->
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li <?= LinkHelper::left_bar_active(Url::to(['default/index']))?>>
          <a href="<?= Url::to(['default/index'])?>">
            <i class="fa fa-dashboard"></i> <span>Dashboard</span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-spoon"></i>
            <span>Food</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li <?= LinkHelper::left_bar_active(Url::to(['food/index']))?>><a href="<?= Url::to(['food/index'])?>"><i class="fa fa-circle-o"></i> List Food</a></li>
            <li <?= LinkHelper::left_bar_active(Url::to(['food/food-cat']))?>><a href="<?= Url::to(['food/food-cat'])?>"><i class="fa fa-circle-o"></i> Categories</a></li>
            <li <?= LinkHelper::left_bar_active(Url::to(['food/food-type']))?>><a href="<?= Url::to(['food/food-type'])?>"><i class="fa fa-circle-o"></i> Types</a></li>
          </ul>
        </li>
        <li <?= LinkHelper::left_bar_active(Url::to(['testimoni/index']))?>>
          <a href="<?= Url::to(['testimoni/index'])?>">
            <i class="fa fa-comment"></i> <span>Testimoni</span>
          </a>
        </li>
        <li <?= LinkHelper::left_bar_active(Url::to(['account/index']))?>>
          <a href="<?= Url::to(['account/index'])?>">
            <i class="fa fa-user"></i> <span>Account</span>
          </a>
        </li>
        <li <?= LinkHelper::left_bar_active(Url::to(['default/language']))?>>
          <a href="<?= Url::to(['default/language'])?>">
            <i class="fa fa-language"></i> <span>Language</span>
          </a>
        </li>
        <!-- <li >
          <a href="<?= Url::to(['default/sad'])?>">
            <i class="fa fa-language"></i> <span>sad</span>
          </a>
        </li> -->
        <li class="header">OTHER</li>
        <li class="">
          <a href="<?= Url::home()?>" target="_blank">
            <i class="fa fa-desktop"></i> <span>Application</span>
          </a>
        </li>
      </ul>
    </section>

modules/admin/views/layouts/_nav_bar_top.php
<?php

use yii\helpers\Url;

$session = Yii::$app->session;
//$session->open();
?>
<nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="<?= Url::base()?>/vendor/AdminLTE/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">
              <span class="hidden-xs"><?= ($session->get('username')) ? $session->get('username') : '["Username"]' ?></span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="<?= Url::base()?>/vendor/AdminLTE/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

                <p>
                  <?= ($session->get('username')) ? $session->get('username') : '["Username"]' ?> - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              <!-- <li class="user-body"> -->
                <!-- <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#">Followers</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Sales</a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#">Friends</a>
                  </div>
                </div> -->
                <!-- /.row -->
              <!-- </li> -->
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="<?= Url::to(['account/profile'])?>" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="<?= Url::to(['default/logout'])?>" class="btn btn-default btn-flat">Sign out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <!-- <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li> -->
        </ul>
      </div>
    </nav>

modules/admin/views/layouts/main-login.php
<?php

use yii\helpers\Url;
use app\assets\AppAssetModulesLogin;

AppAssetModulesLogin::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?= $this->title;?> | Admin Panel</title>
  <?php $this->head() ?>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition login-page">
<?php $this->beginBody() ?>
  <?= $content;?>
<?php $this->endBody() ?>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-blue',
      radioClass: 'iradio_square-blue',
      increaseArea: '20%' /* optional */
    });
  });
</script>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/main.php
<?php

use yii\helpers\Url;
use app\assets\AppAssetModules;

AppAssetModules::register($this);

$session = Yii::$app->session;

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title><?= $this->title;?></title>
    <?php $this->head() ?>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="<?= Url::to([''])?>" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b> P</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>ADMIN</b> PANEL</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <?= $this->render('_nav_bar_top');?>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <?= $this->render('_left_bar');?>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
      <?= $content ?>
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.18
    </div>
    <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE</a>.</strong> All rights
    reserved.
  </footer>

  <!-- Control Sidebar -->
  <?= $this->render('_control_sidebar');?>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>